# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eva' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Eva

pod 'FSCalendar'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Firestore'

end
